### ISSUE TITLE
我想问下更新后怎么重启 nginx？

### ISSUE THREAD

**Issue by qurge** [ilaipi/acme.sh-docker#1]

**Comment by ilaipi** [comment]
我的方案是通过crontab，每天定时重启nginx

**Comment by qurge** [comment]
> 我的方案是通过crontab，每天定时重启nginx

是本机的 cron 还是 docker 的 cron ?

**Comment by ilaipi** [comment]
你nginx怎么部署的？这个仓库跑起来的docker容器，只是acme服务本身，没有nginx。

不过就算你是用docker跑的另外的nginx容器，也应该在host配置cron，直接`docker restart nginx(nginx容器名字)`

**Comment by ilaipi** [comment]
你nginx怎么部署的？这个仓库跑起来的docker容器，只是acme服务本身，没有nginx。

不过就算你是用docker跑的另外的nginx容器，也应该在host配置cron，直接`docker restart nginx(nginx容器名字)`

**Comment by qurge** [comment]
> 你nginx怎么部署的？这个仓库跑起来的docker容器，只是acme服务本身，没有nginx。
> 
> 不过就算你是用docker跑的另外的nginx容器，也应该在host配置cron，直接`docker restart nginx(nginx容器名字)`

acme 一个容器，nginx 一个容器

**Comment by ilaipi** [comment]
```
# 重启nginx 并执行reload
1 0 1,15 * * cd /path/to/nginx && docker-compose up -d --build nginx && docker-compose exec nginx nginx -s reload
```

**Comment by qurge** [comment]
> ```
> # 重启nginx 并执行reload
> 1 0 1,15 * * cd /path/to/nginx && docker-compose up -d --build nginx && docker-compose exec nginx nginx -s reload
> ```

嗯嗯，谢谢了

**Comment by ilaipi** [comment]
```
# 执行reload
# 每月1号 15号 0:01执行
1 0 1,15 * * cd /path/to/nginx && docker-compose exec nginx nginx -s reload
```

**Comment by qurge** [comment]
![image](https://user-images.githubusercontent.com/29910922/125422123-f893f2db-5731-4b02-8f6b-1364a0129f57.png)
这个是你吧

**Comment by ilaipi** [comment]
> ![image](https://user-images.githubusercontent.com/29910922/125422123-f893f2db-5731-4b02-8f6b-1364a0129f57.png)
> 这个是你吧

是我🌝

**Comment by mtgq** [comment]
![image](https://user-images.githubusercontent.com/29910922/126024141-698344f4-f3b5-4632-a09e-6b2884b14da6.png)
大佬，我在 docker-compose 文件中已经这样设置了，按道理应该会被保存在容器 acme  的 ~/.acme.sh/account.conf 这个文件中，但是我在容器中没有找到这个文件 ？
